### ISSUE TITLE
Search by File Name

### ISSUE THREAD

**Issue by hacdias** [hacdias/caddy-filemanager#1]
Should a search functionality be added or not?

**Comment by joeblew99** [comment]
i think so..  

Bleve is great for the job. I used it now on two projects and it was impressive.

http://www.blevesearch.com/

Caddy uses Bleve already btw 
http://www.blevesearch.com/docs/Applications-using-bleve/

**Comment by hacdias** [comment]
Thanks ;) I'll see that.

**Comment by nwgat** [comment]
caddy uses bleve for its built-in search

**Comment by hacdias** [comment]
Hello @nwgat: I'll just implement a basic search by file name. If someone wants a more powerful search, they can use the plugin built specially for it. BTW, it's already working 😄

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#113
