### ISSUE TITLE
Initial path does not correspond to the root specified in Caddyfile

### ISSUE THREAD

**Issue by MSF-Jarvis** [hacdias/caddy-filemanager#10]
When I set the file manager plugin to show up at /manage, it shows me a listing of /root, which is coincidentally both my Caddyfile's location and my home dir since I run everything as root on my server. This behavior is undesirable in my opinion and many would like it to honor the root specified in the Caddyfile.

**Comment by hacdias** [comment]
Hello!

Try:

```
filemanager {
  show        folder_you_want_to_browse
  on            /manage
}
```

**Comment by hacdias** [comment]
And... it is supposed to show the root set on Caddyfile.

**Comment by MSF-Jarvis** [comment]
I am using exactly that, but I feel it should be defaulting to the root
specified rather than the Caddyfile location

**Comment by MSF-Jarvis** [comment]
I did do a simple 

```
root /var/www/roms
filemanager {
  on            /manage
}
```

To end up looking at my /root dir, I'll try to run a couple of tests and get back to you so closing it for now.

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#121

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#122
