### ISSUE TITLE
Ability to show file checksum on directory listing 

### ISSUE THREAD

**Issue by mevric** [hacdias/caddy-filemanager#11]
it would be nice to show checksum value for a file. This would be similar to the file size that is displayed by default.

**Comment by hacdias** [comment]
Hello @mevric!

I understand what you want, but, here's the big question: wouldn't show a checksum for every single file make the File Manager slow to open? I think it would, don't you?

What I think we could do: we could put like placeholders and when if we clicked on them/hover, it would show the checksum. It could be MD5, SHA-1, everything that Go supports. Or, you could select a file (or a bunch of files) an then click in an option on the top bar to show the desired checksum. What do you think?

I'm really glad for your idea :D

**Comment by mevric** [comment]
:) I agree with the issue mention. Also the solution of displaying the checksum  on demand for each file seems reasonable. 

I am new to filemanager and will spend some time going over the code today. 
Thanx for the quick response.

**Comment by hacdias** [comment]
Hey! You're welcome. I will mark this issue as something to do.

**Comment by hacdias** [comment]
So much time since the last reply! God! I'll implement this today @mevric !!
