### ISSUE TITLE
Pregenerate assets

### ISSUE THREAD

**Issue by wenerme** [hacdias/caddy-filemanager#14]
Always got this when I use godep.

```
# yikaiye.com/proxier/vendor/github.com/hacdias/caddy-filemanager/assets
vendor/github.com/hacdias/caddy-filemanager/assets/assets.go:19: undefined: Asset
```

**Comment by hacdias** [comment]
Hello!

Just navigate to ```vendor/github.com/hacdias/caddy-filemanager``` and execute ```go generate```. :D

**Comment by hacdias** [comment]
Check [this section on README](https://github.com/hacdias/caddy-filemanager#note-for-developers) for further details.
