### ISSUE TITLE
Make breadcrumb navigation more intuitive...

### ISSUE THREAD

**Issue by justrjlewis** [hacdias/caddy-filemanager#18]
So currently we have this: https://cl.ly/152l1B0b4705.  I think the full path should show, or the up-on-level icon should be next to the current location.
![caddy_dev_breadcrumb1](https://cloud.githubusercontent.com/assets/1163648/17644006/c3136850-6140-11e6-8c94-6094c9fcde31.png)
![caddy_dev_breadcrumb2](https://cloud.githubusercontent.com/assets/1163648/17644007/c3143a46-6140-11e6-8d91-f91375c918bf.png)

The only reason that I brought it up is because I clicked "Hugo" several times, before it occurred to me to click the arrow to only go up one level...which could just be me, but I didn't automatically assume the arrow was for up-one-level.

Maybe even just serving an icon in between would make it stand out more like this: 
![caddy_dev_breadcrumb3](https://cloud.githubusercontent.com/assets/1163648/17644035/a4d8dd06-6141-11e6-9d8a-20a2c4df4363.png)

**Comment by hacdias** [comment]
I've got an idea and I will work on it. There will only be two itens: the current file and its parent. BUT, when you put your mouse over the parent directory (or the icon on left, I've to choose - help me!), it will show a dropdown list with the parents of parents (... of parents) until it reaches the base directory. There you will be able to select what you want! What do you think?

**Comment by justrjlewis** [comment]
Oh! ...something like this?

![caddy_dev_breadcrumb4](https://cloud.githubusercontent.com/assets/1163648/17645484/ebda16ae-616c-11e6-969a-0ffd63008eb1.png)

**Comment by justrjlewis** [comment]
What about something like this:

state: ![caddy_dev_breadcrumb_state](https://cloud.githubusercontent.com/assets/1163648/17645497/959423b0-616d-11e6-984d-36164715f6e7.png)
hover/click: ![caddy_dev_breadcrumb_hover](https://cloud.githubusercontent.com/assets/1163648/17645498/9919a7f8-616d-11e6-8fa3-c7b393897df0.png)

**Comment by hacdias** [comment]
Maybe the second one. I was thinking about doing it vertically. Don't you think so?

**Comment by justrjlewis** [comment]
I tried it that way at first, but came across a conundrum — would the hierarchy be:

parent 
 > parent
    > root

or 

Root
> parent
   >parent

and how would the user know?

**Comment by hacdias** [comment]
For the path `Imagens/2016-06/11/file.jpeg`, it would be:

```
11
2016-06
Imagens
File Manager/Root/Whatever
```

So, it should start from the nearest parent and go to the root.

**Comment by hacdias** [comment]
Are you willing to do this, or should I do it?

**Comment by justrjlewis** [comment]
I can give it a go! 👍

**Comment by hacdias** [comment]
Hey @justrjlewis, any news? :)

**Comment by justrjlewis** [comment]
@hacdias I haven't gotten two it yet.  I had three site launches and I'm still in the thick of it.

**Comment by hacdias** [comment]
Sure ;) Good work!

**Comment by justrjlewis** [comment]
Thanks!  I've got one to launch tmw and one more then I'm free'd up until the next round. 😸

**Comment by hacdias** [comment]
Hey @justrjlewis, I'll start doing this now if you don't mind.

**Comment by hacdias** [comment]
@justrjlewis, I've made some changes and I would like you to try. I think it's fine, but not great yet. WHat do you suggest?

**Comment by justrjlewis** [comment]
Oh awesome, let me download!
