### ISSUE TITLE
[Feature Request] Config Flag to disable some features

### ISSUE THREAD

**Issue by Bitti09** [hacdias/caddy-filemanager#19]
It would be good to have a Flag for disabling one or all of theese things:

- Command bar
- New File/Folder button
- Edit Button

**Comment by hacdias** [comment]
Hey @Bitti09,

Yes, I agree that this plugin could be "modular", but disabling those 3 features you just get something like the native [browse](https://caddyserver.com/docs/browse) middleware. Why not just use it? :confused:

**Comment by hacdias** [comment]
Ping @Bitti09

**Comment by Bitti09** [comment]
@hacdias filemanager has a better default  site for example
and making thoose 3 modular would allow to  limit a folder view to new file/folder & edit only

**Comment by hacdias** [comment]
Sure! I'll do it then :)

**Comment by hacdias** [comment]
```
allow_new         [true|false]
allow_edit        [true|false]
allow_commands    [true|false]
```

Sounds good?

**Comment by Bitti09** [comment]
@hacdias  :+1:

**Comment by Bitti09** [comment]
@hacdias  
do i get the updated filemanager when using getcaddy.com ? or is selfbuild required at the moment ?

**Comment by hacdias** [comment]
At the moment you can only use this by building it by yourself. But take
care! As I'm adding more functionalities mentioned in other issues, I do
not grant that everything is going to work.

You should wait till I remove the big advice from the readme that says that
this might be unstable ATM.

Hope it helps!

P.S.: This feature is supposed to be working. But some of the others might
conflict yet. Try it. If you find any error, tell me. Just don't use it in
production! :)

**Comment by Bitti09** [comment]
@hacdias  so config flags = stable
user management = unstable?
ok

**Comment by hacdias** [comment]
Hey @Bitti09!

I think that everything is more or less stable right now, so you can try everything. But caddy-hugo wasn't still updated to work with this changes. That's why I'm not going to remove the advice from the readme now.
