### ISSUE TITLE
Improvements to Drag and Drop

### ISSUE THREAD

**Issue by hacdias** [hacdias/caddy-filemanager#2]
- [x] Move files with drag and drop;
- [x] Upload files dragging them to the directory icon.

**Comment by pwFoo** [comment]
Is multiple file / recursive directory upload possible or planned?

**Comment by hacdias** [comment]
Hey @pwFoo! Right now you can upload multiple files. I'm not 100% sure about uploading directories.

**Comment by Timmmm** [comment]
In addition to uploading by dragging files onto a directory icon it should be possible to drop files on the page background to upload them to the current directory.

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#114
