### ISSUE TITLE
Config option to enable raw mode by default

### ISSUE THREAD

**Issue by jahands** [hacdias/caddy-filemanager#20]
I'd love to use this to host screenshots, but dislike needing to specify raw=true.
Any way this could be added to config?
Eg.
```
filemanager {
    raw
}
```

**Comment by jahands** [comment]
Actually, a better solution may be to just put filemanager on files.domain.com and browse on f.domain.com, etc.

**Comment by jahands** [comment]
Derp. This is solved by using a seperate subdomain/domain like this:
```
file.example.com {
    root /files
}
```

**Comment by hacdias** [comment]
Hello! Yes, I think that using a dubdomain for that is a better way, than displaying everything in "raw" mode. Another alternative could be:

```
example.com {
    root /files
    filemanager {
        show /files
        on /upload
    }
}
```
