### ISSUE TITLE
Directories and files permissions

### ISSUE THREAD

**Issue by dustinromey** [hacdias/caddy-filemanager#21]
Looks like filemanager is happy to serve files that begin with a "." Perhaps there should be an option to not allow it to, or perhaps even it should have to be expressly allowed in the caddyfile config?

**Comment by hacdias** [comment]
I am thinking... should we only have an option to block "dot files" or have an option to restrict the access to folders/files/patterns the user wants?

**Comment by dustinromey** [comment]
A block directive certainly sounds more flexible, and I presume not much more effort. Are you thinking of applying a regex to the file name or something more?

I'm trying to think of other things you might want to block, and don't come up with much more. Suggestions?

**Comment by dustinromey** [comment]
And I actually think the opposite given caddy's focus is for less technical types of people. Some may not even know they don't want to serve dot files. Seems like a good default to hide them, or require some step to allow them.

**Comment by hacdias** [comment]
So, I'm thinking about creating four new options:

+ `allow` - specific files or folders
+ `allow_r` - regex
+ `block` - specific files or folders
+ `block_r` - regex

There would be a special keyword, `dotfiles`, and by default, the option `block dotfiles` would be active. What do you think?

**Comment by dustinromey** [comment]
Sounds good!
