### ISSUE TITLE
Problems uploading files on Safari 9.11

### ISSUE THREAD

**Issue by dustinromey** [hacdias/caddy-filemanager#22]
No response to any of the buttons, nor drag/drop a file.

**Comment by hacdias** [comment]
May you please see the console on the developer tools to check which is the error?

**Comment by dustinromey** [comment]
<img width="1236" alt="screen shot 2016-08-21 at 7 16 11 am" src="https://cloud.githubusercontent.com/assets/828343/17836866/35672ea8-676f-11e6-8d35-0d3fc78fa2cf.png">

**Comment by hacdias** [comment]
That's really strange. I don't get that error in any of the browsers I use.
Yes, that's really, really easy to fix, but I'll search about constants not
being allowed in strict mode. When I get home, I'll fix that. :) Thanks.
