### ISSUE TITLE
About fonts.googleapis.com

### ISSUE THREAD

**Issue by jet10000** [hacdias/caddy-filemanager#26]
so, China users can't visit Google api , How custom it?

**Comment by Bitti09** [comment]
@hacdias what about a config ?
like: china_fonts :  false = google api ; true = china server adress

**Comment by hacdias** [comment]
Hmm... You're true... Probably it is the best option @Bitti09, thanks! 😃

**Comment by hacdias** [comment]
@Bitti09, which is the link I should use for China users? `fonts.useso.com` doesn't seem to be working here.

**Comment by hacdias** [comment]
I'm closing this issue because the problem was already [solved by Google](http://stackoverflow.com/questions/25677460/google-font-make-page-load-very-slow-in-china/39752405#39752405).

**Comment by jet10000** [comment]
Cool!
