### ISSUE TITLE
Feature-Request: Download/Upload directory structure as archiv (zip, ..)

### ISSUE THREAD

**Issue by fanningert** [hacdias/caddy-filemanager#29]
What are you thinking about a upload/download function for a complete directory structure (incl. files) as archiv (zip, tar,...)?

**Comment by hacdias** [comment]
That's an interesting idea! I'll mark this as to-do.

**Comment by hacdias** [comment]
Hello @fanningert! I think you'll be happy to know that I've implemented this! On the next caddy release, hopefully, you can download directories, or download specific files, as zip, tar, tar.gz or tar.bz2!

**Comment by fanningert** [comment]
I will test it, when it is out. And thanks for your work.

**Comment by hacdias** [comment]
You're welcome! And sorry for the delay!
