### ISSUE TITLE
Feature-Request: Button for directory creation

### ISSUE THREAD

**Issue by fanningert** [hacdias/caddy-filemanager#30]
I know it is possible to create a directory over command. But this function is not for all users perfect. So a extra button for directory creation is perfect, like the file create button.

**Comment by hacdias** [comment]
Wait... the File Create button doesn't create folders? Try typing a name without an extension please. I thought it worked :(

**Comment by hacdias** [comment]
I've tried it here and it works. Just let me know if it works there too 😄 Anyway, thanks for the suggestion!

**Comment by fanningert** [comment]
Thanks, its works.
But a little text for information about this two features (without extension a directory, with extension a file) a great action for usability. (Above the input field for example)

**Comment by hacdias** [comment]
I'll add it 😄 Thanks!

**Comment by fanningert** [comment]
But I think I found a little bug. 
When I created a file or directory and I click a second time on the create button, no input field is visible.

**Comment by hacdias** [comment]
You're absolutely right! I'll check that too! Thank you 😄 I promise I'll do it as soon as I've time.

**Comment by fanningert** [comment]
No problem. Thanks for the create addon.

**Comment by hacdias** [comment]
You're welcome! And thank you too, for being its user! 😃
