### ISSUE TITLE
Feature-Request: Show Command output

### ISSUE THREAD

**Issue by Bitti09** [hacdias/caddy-filemanager#32]
Would be nice to see the output  of a command for example:
download progress for wget or
clone/push progress for git

**Comment by hacdias** [comment]
Hello @Bitti09! I thought that it was working like that 😕 I'll take a look as soon as I can.

**Comment by hacdias** [comment]
This should be done with a websocket right? Or there is a better way? @Bitti09

**Comment by hacdias** [comment]
@Bitti09, what if the command asks you for input? Do you think it would be an interesting feature to allow the user to interact with the command after sending it?

**Comment by hacdias** [comment]
@Bitti09 check [this](https://dl.dropboxusercontent.com/u/100414923/video.webm) out!

**Comment by hacdias** [comment]
This is officially done. Right now I'm not thinking about allowing interactivity with the commands. Only if someone requests it.

**Comment by Bitti09** [comment]
@hacdias  the command output (like git in your short video) is enough. I don't  need any interactivity after initial  command. :+1:
