### ISSUE TITLE
"show foo on /bar" configuration not working as expected

### ISSUE THREAD

**Issue by anansii** [hacdias/caddy-filemanager#34]
Hi

running Caddy 0.9.3 on Windows I'm not able to show the contents of a file if the URL is not pointing to the actual folder.

Action: Using URL http://www.domain.tld/files
Expected behavior:  filemanager shows files in C:/Sites/domain.tld/www/dist
Result: This works

Action: Clicking on index.md to see its contents
Expected behavior:  filemanager shows contents of C:/Sites/domain.tld/www/dist/index.md
Result: [ERROR 500 /files/index.md] open C:\Sites\domain.tld\www\dist\files\index.md: The system cannot find the path specified.

Configurations tried:

```
filemanager {
    show C:/Sites/domain.tld/www/dist
    on /files
}
```

```
filemanager /files {
    show C:/Sites/domain.tld/www/dist
}
```

```
filemanager {
    show ../../../Sites/domain.tld/www/dist
    on /files
}
```

those were used inside 

```
root C:/Sites/domain.tld/www/dist
basicauth /files user password
```

What am I doing wrong?

Update: It only doesn't work for files with the .md ending. Turning off the markdown plugin fixed this. However, the goal was to have easy editing access to those md files. :(

**Comment by hacdias** [comment]
Hello @anansii!

Sorry, but I can't help you with this. Even though I know which is the problem: the *markown* plugin. It has a bigger priority than the *filemanager* plugin so it will try to render that file. Then, as it doesn't exist, it results in an error.

The only solution for this is to put *filemanager* before *markdown* in the directives list, but I'm not sure if it would be a good idea. What do you think?

**Pinging @mholt**

**Comment by anansii** [comment]
Hi

I found this: https://github.com/mholt/caddy/issues/409
I believe the suggested solution there is indeed to put the custom code higher up in the directives list.

Thanks for taking the time :)

**Comment by mholt** [comment]
Yup, if you want filemanager to have priority over rendering markdown files, then you need to move filemanager up on the list.

**Comment by hacdias** [comment]
I'm going to close this now because you already know what to do @anansii! Anything else, tell me! 😄

**Comment by anansii** [comment]
I'm sorry, I'm confused.  Changing the order inside my Caddyfile was the first thing I tried and it didn't work, so I assumed the plugin needs to register itself higher in the "execution order list". I am quite new to Caddy and not familiar at all with its code, but that's what I gathered from the other issue. Am I wrong?

**Comment by mholt** [comment]
The order in the Caddyfile doesn't matter, you're right. It has to change
in the code.
