### ISSUE TITLE
filemanager middleware needs to register itself higher up the directive chain

### ISSUE THREAD

**Issue by anansii** [hacdias/caddy-filemanager#35]
As mentioned here https://github.com/hacdias/caddy-filemanager/issues/34 
the filemanager middleware needs to register itself higher up the directive chain than the markdown middleware for it to be able to show the contents of files that are handled by the markdown middleware.

In here https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go
filemanager needs to be above markdown.

**Comment by hacdias** [comment]
Done 😄
