### ISSUE TITLE
How to build Caddy with File Manager?

### ISSUE THREAD

**Issue by nwgat** [hacdias/caddy-filemanager#38]

**Comment by hacdias** [comment]
Hello @nwgat!

To build this plugin alongside with Caddy, you need, of course, to have Go installed and all of that. To activate the plugin, you should add to [run.go](https://github.com/mholt/caddy/blob/master/caddy/caddymain/run.go#L20) the line `_ "github.com/hacdias/caddy-filemanager"` and then you just have to build Caddy in the normal way using `go build`.

Hope it helps. If you need more steps tell me!

**Comment by nwgat** [comment]
i was missing `_` lol 
also i keep getting

```
403 Forbidden

Try reloading the page or hitting the back button. If this error persists, it seems that you may have found a bug! Please create an issue at hacdias/caddy-filemanager repository on GitHub with the code below.

stat .: permission denied
```

my caddyfile is 

```
: {
root /home/user/www/
        basicauth / admin pass
        filemanager /rtdl {
            allow_commands false
            admin:
            allow_commands true
            allow_command  rm
            allow_command  mv
            allow          dotfiles
}
        tls self_signed
        #markdown
        #gzip
        #fastcgi / /run/php/php7.0-fpm.sock php
}

```

**Comment by hacdias** [comment]
@nwgat, I don't think error is not related to FM. Try checking if Caddy has permissions to access that folder.

**Comment by nwgat** [comment]
well caddy with browse works fine
can it be that filemanager runs before basicauth or something?

here is the amd64 binary
https://transfer.sh/B3ONw/caddy

**Comment by hacdias** [comment]
File Manager works flawlessly with Basic Auth. 

I can't try your binary because I'm on Windows :/

But everything is working here. The error is clear (`stat .: permission denied`). The process can't open the file. The Operating System returns permission denied :|

**Comment by hacdias** [comment]
@nwgat can you try giving more permissions to the files? Just to try it out.

**Comment by nwgat** [comment]
got it working in the end, seems to be permissions

**Comment by hacdias** [comment]
Cool @nwgat! I'm gonna close this 😄 If you have any suggestion, please tell me!
