### ISSUE TITLE
 cannot find package "github.com/spf13/hugo/parser"

### ISSUE THREAD

**Issue by tmacychen** [hacdias/caddy-filemanager#39]
Hi,When building the FM with caddy,I find this error. Then I just run "go get github.com/spf13/hugo/parser ", but it doesn't work. So I find this project url is https://github.com/spf13/hugo , and parser url is "https://github.com/spf13/hugo/tree/master/parser" .
What shoud I do?

**Comment by tmacychen** [comment]
It's seams like network problem,  I just try again and it works.
When I run `./build.bash` after go generate, I find an error report 
`>./build.bash  
# github.com/hacdias/caddy-filemanager/file
../../../hacdias/caddy-filemanager/file/listing.go:40: not enough arguments in call to u.FileSystem.OpenFile`
Does OpenFile function need a context param  ?

**Comment by hacdias** [comment]
That's strange! It should work, which version of Go are you using?

**Comment by hacdias** [comment]
Oh... sorry... it didn't need it before!!!! I'll fix it as soon as I can. Thanks

**Comment by hacdias** [comment]
Solved!
