### ISSUE TITLE
Allow other Front Matter formats

### ISSUE THREAD

**Issue by chesedo** [hacdias/caddy-filemanager#4]
The filemanager plugin currently only supports creating Front Matter in the JSON format. Is it possible to also add support for TOML and YAML?

This will allow other caddy plug-ins that use filemanager to create files in the desired Front Matter format.

**Comment by hacdias** [comment]
Thanks ;)

**Comment by hacdias** [comment]
Done.

**Comment by chesedo** [comment]
Thanks

**Comment by hacdias** [comment]
You're welcome ;)
