### ISSUE TITLE
Add PHP as editable file type

### ISSUE THREAD

**Issue by sinni800** [hacdias/caddy-filemanager#42]
I am sure ACE supports PHP editing and this change would be trivial

There are a lot of modes available: https://github.com/ajaxorg/ace/tree/master/lib/ace/mode 

Optionally, allow more file types to be added using directives (and their respective ace mode, maybe? Though that would be a lot of coupling...) as per https://github.com/hacdias/caddy-filemanager/blob/master/file/info.go#L100

**Comment by sinni800** [comment]
#44 Added a PR for now

**Comment by hacdias** [comment]
Hello @sinni800! Thanks for this suggestion! The funny thing is that I can edit those files without adding them to the exceptions because they are text files. Which OS are you using?

**Comment by hacdias** [comment]
I'm using mimetypes to check the type of the file and PHP can have these:

```
text/php
text/x-php
application/php
application/x-php
application/x-httpd-php
application/x-httpd-php-source
```

Probably your computer doesn't consider it a `text/`. I'm going to add the others ASAP.

**Comment by sinni800** [comment]
Crazy, I am actually on Archlinux for the server. 

I don't know if I need any extra things though

**Comment by hacdias** [comment]
I merged your PR right now but in the weekend I hope I've time to take a look at this. Thanks! 😄
