### ISSUE TITLE
Allow ACE and fonts to be loaded locally

### ISSUE THREAD

**Issue by sinni800** [hacdias/caddy-filemanager#43]
I don't want to leave a fingerprint on other servers about things I do on my local server... Would it be possible to include ACE and the fonts with the assets? Ace is loaded with a fixed version anyway and it would help if the server is deployed in a local in-company server.

**Comment by hacdias** [comment]
I'm going to think about this, but I think it would make the plugin a lot heavier. But I'll check it out 😄

**Comment by jet10000** [comment]
cdnjs.cloudflare.com and googleapis still blocked by china firewall.

**Comment by hacdias** [comment]
Hey @jet10000 and @sinni800! Sorry for not updating this issue. I'll check it.

**Comment by goxofy** [comment]
same issue thank you!

I wanna deploy caddy with filemanager in my in-company net.

**Comment by sinni800** [comment]
Well @hacdias if you consider how ready people are to create a hubdreds of mb thick tree of node dependencies I think you're quite fine deploying like 3mb more
