### ISSUE TITLE
files links are generated with absolute path

### ISSUE THREAD

**Issue by apremalal** [hacdias/caddy-filemanager#45]
Hi Devs!,

I got the following Caddyfile

```
localhost:8083/portal {
    filemanager admin {
        show           webapps/portals/
        allow_new      true
        allow_edit     true
        allow_commands true
        block          dotfiles
    }
    root  webapps/portals/
    gzip
    log    logs/caddyaccess.log
}
```
To get to the file manager I can visit` http:://localhost:8083/portal/admin`

Then all the file manager links are generated as below
/admin/file1.txt
/admin/file2.txt

I was expecting 
/portal/admin/file1.txt
/portal/admin/file2.txt

Have I misconfigured or is this not achievable?

**Comment by hacdias** [comment]
Hello @apremalal! Sorry for the delay.

I think this is, actually, a bug on File Manager, but as an workaround you can try:

```
localhost:8083/portal {
    filemanager /portal/admin {
        show           webapps/portals/
        allow_new      true
        allow_edit     true
        allow_commands true
        block          dotfiles
    }
    root  webapps/portals/
    gzip
    log    logs/caddyaccess.log
}
```

**Comment by apremalal** [comment]
Hi @hacdias,

Thanks for the response and for the quick fix. 

Suggested workaround is not going to work. To get to the file manager users will need to go to 
/portal/portal/admin and the generated links will have /portal/admin which is not going to be serverd by the file manager.

Actually I tried your suggestion and the results are same as above.

How can I get a new caddy distribution with your fix?. I tried downloading the latest version with filemanger plugin but it haven't had the fix.

**Comment by hacdias** [comment]
@apremalal you're right. 😄

**Comment by hacdias** [comment]
Sorry!

**Comment by hacdias** [comment]
@apremalal IDK when will the new version be available for download at caddyserver.com. The only way now is building this from source.

@mholt, when are you going to update the plugins?

**Comment by apremalal** [comment]
@mholt is there a documentation on bulding caddy with selected plugins?. I wasn't able to find a one.

**Comment by mholt** [comment]
@apremalal  I've replied here to your question: https://forum.caddyserver.com/t/building-caddy-with-latest-selected-plugins/947/2?u=matt

@hacdias As soon as I can get around to it, sorry! 😓 I'd rather get the new build server working, frankly, so I won't have to do this manually anymore.

**Comment by apremalal** [comment]
@mholt thanks for the response

**Comment by hacdias** [comment]
Hey @mholt! Okay, no problem ;)
