### ISSUE TITLE
'directory' folder missing?

### ISSUE THREAD

**Issue by outhud** [hacdias/caddy-filemanager#47]
I'm trying to get caddy-hugo, using go get, but it gives:

> package github.com/hacdias/caddy-filemanager/directory: cannot find package "github.com/hacdias/caddy-filemanager/directory" in any of:

Sure enough, I don't see a directory folder here in caddy-filemanager.

**Comment by hacdias** [comment]
Hi @outhud! Sorry for the delay 😞 Caddy-Hugo is not compatible with the newest version of File Manager. I'll update it ASAP.

**Comment by hacdias** [comment]
I think it works now! 😄
