### ISSUE TITLE
Creating a page with number content only results in PANIC and response-code 500

### ISSUE THREAD

**Issue by ebudan** [hacdias/caddy-filemanager#49]
This is a bit of an edge case, but...  who knows who might need a page with a number. (I wouldn't, but hit this while tracking down something else.)

If you use Filemanager to create a page containing only something that can be parsed as a number, `handlers/put.go:PreProccessPUT()` will panic at the following point:

    mainContent := data["content"].(string)

A quick inspection shows that saving page content "1" PUTs

    { content: 1 }

while page content "a" PUTs

    { content: "a" }

This is deliberately done in `_embed/public/js/form2js.js`, function convertValue(), so I'm not certain whether client or server-side would be the place to cover the case.

**Comment by ebudan** [comment]
Just realised: this also comes up if you try to delete all page content and save an empty page.

**Comment by hacdias** [comment]
Fixed. Thanks 😄
