### ISSUE TITLE
upload/create PUT results in 404

### ISSUE THREAD

**Issue by ptman** [hacdias/caddy-filemanager#51]

**Comment by hacdias** [comment]
Hi @ptman. Thanks for opening this and sorry for this bug.

**Comment by ptman** [comment]
No, thank you for fixing bugs so quickly.

Now however, when uploading files (not when creating), the files get the name prefixed with "undefined"

**Comment by hacdias** [comment]
@ptman that's strange... it's not happening here. I can check it better. It must be related to the JavaScript. Can you please try to `go generate`? Just to make sure.

**Comment by ptman** [comment]
I did manage to remember go generate this time. The result stays the same after:

    go get -u github.com/hacdias/caddy-filemanager
    go generate github.com/hacdias/caddy-filemanager
    ./build.bash
    ./caddy

**Comment by hacdias** [comment]
@ptman I'll check that ASAP.

**Comment by hacdias** [comment]
@ptman I can't reproduce your error :/

**Comment by ptman** [comment]
I updated caddy and caddy-filemanager
I ran go generate
I built caddy using ./build.bash
running caddy, I went to the filemanager
I chose Upload (up arrow on top right)
I chose a file (README.md from caddy-filemanager)
The file was uploaded, but it wasn't named "README.md", but "undefinedREADME.md"

**Comment by hacdias** [comment]
Hey Paul! You choose the button! I was just trying to drag and drop. When I
arrive home I'll check that. I forgot that since dragging and dropping is
easier.

**Comment by ptman** [comment]
I don't have anywhere to drag from, as I only have my browser and a bunch of terminals

**Comment by hacdias** [comment]
Sorry, I haven't checked this yet. But today I'll fix this. I promise. I'm
not home right now but as soon as I get there I'll fix this!

**Comment by hacdias** [comment]
@ptman fixed!!!

**Comment by ptman** [comment]
So it is, thank you!
