### ISSUE TITLE
Please change the font mirror from googleapis to locally

### ISSUE THREAD

**Issue by GalvinGao** [hacdias/caddy-filemanager#54]
# Issue
As long as this plugin have been wild using in all of the world, googleapis might not a perfect solution to provide font files. They might a little big for filling in to the file manager plugin, but it is really useful if you are using a local network that don't have any network connection to internet.

# Solution
So please change [the template (hacdias/caddy-filemanager/blob/master/_embed/templates/base.tmpl)](https://github.com/hacdias/caddy-filemanager/blob/master/_embed/templates/base.tmpl#L8#L9) **line 8 to 9**, to the locally file address.

# **If you have any problem for changing this, just @mention me. Huge thanks to that!**

**Comment by GalvinGao** [comment]
@hacdias have a look~

**Comment by hacdias** [comment]
Hey @GalvinGao! Gonna check this.

**Comment by GalvinGao** [comment]
Thanks so much about this! It gonna helps me out a lot. Thanks!
