### ISSUE TITLE
Why insert_drive_file so large

### ISSUE THREAD

**Issue by pepa65** [hacdias/caddy-filemanager#56]
I almost think I'm missing something, but I'm now on Caddy 0.9.4 and it still looks like the attached screenshot. Can anything be done to make it look more.... 'professional' or 'nice' or... Is something wrong with the way I'm invoking filemanager??
![filemanager](https://cloud.githubusercontent.com/assets/6505000/21505248/1936ca7a-cc98-11e6-9041-7b3bc13eb53e.png)

**Comment by hacdias** [comment]
Hello @pepa65!

That isn't supposed to happen! It just means that you are unable to load the Google Icons Font. I can also see that you don't have the Roboto font loaded. Do you have any problems connecting the Google servers? Like this URL: https://fonts.googleapis.com/icon?family=Material+Icons .
 
Though, previously today, I've already changed this to have everything being loaded locally without any need of Internet. But those changes aren't available yet on ```caddyserver.com```.

**Comment by pepa65** [comment]
I don't understand why I would have problems connecting to the Google servers... I use gmail, translate, calendar, search. That URL gives:
```
/* fallback */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v19/2fcrYFNaTjcS6g4U3t-Y5ZjZjT5FdEJ140U2DJYC3mY.woff2) format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -moz-font-feature-settings: 'liga';
  -moz-osx-font-smoothing: grayscale;
}
```

**Comment by pepa65** [comment]
Sorry for sounding the alarm... It turned out to be a Firefox setting (not allowing pages to use their own fonts). It probably wouldn't even have worked when the fonts are local. I am good now.

As a feature request though, it would be great to just have a listing of files and their properties like on the file manager's 'detailed' view, so more lines can fit in the screen. (I never use the 'icon' views.)

**Comment by pepa65** [comment]
I guess that would be an extension of the current stylesheet and one more option added to the Switch View toggle.
