### ISSUE TITLE
Mobile related TODOs

### ISSUE THREAD

**Issue by hacdias** [hacdias/caddy-filemanager#59]
- [ ] Make bottom bar look nicer because of the specific buttons on small screens.
- [x] Double tap to open file/directory
- [x] Single selection
- [x] Multiple selection

*References:*

https://developer.mozilla.org/en/docs/Web/API/Touch_events (Handling clicks section)

**Comment by GalvinGao** [comment]
I think you can use an js to listen the event that have been clicked and not clicked, the logic might like:

if you clicked on a not checked file card, then, 
if in next 2 seconds you click (again), then open UI else (user click on wish to select it), 
else (user clicked on already actived file card) deselect this card.

You may check this out~
@hacdias .

**Comment by hacdias** [comment]
Yup! I'll check that out tonight hopefully. I've already left home 😀

I though about:
- Double tap to open
- Tap to select
- Long press to select multiple

What do you think?

**Comment by GalvinGao** [comment]
Good idea! It seems like it need a lot of timers 😝

**Comment by GalvinGao** [comment]
And a lot of 'if' conditions 😉
