### ISSUE TITLE
Reading arrays of tables from config.toml [hugo]

### ISSUE THREAD

**Issue by AstonDavies** [hacdias/caddy-filemanager#69]
When reading a config.toml file that contains arrays of tables (such as menu definitions for Hugo) the following error is thrown when trying to save the file from the filemanager:

`14/Jan/2017:14:25:51 +0000 [PANIC /admin/webdav/config.toml] /home/jeremy/Source/gocode/src/github.com/pelletier/go-toml/tomltree_conversions.go:90 - unsupported value type map[string]interface {}: map[weight:80 identifier:partp name:Part P url:/partp/]`

The config source to produce this is:

```
[[menu.main]]
  identifier = "partp"
  name = "Part P"
  url = "/partp/"
  weight = 80
[[menu.main]]
  identifier = "buildingprojects"
  name = "Building Projects"
  url = "/buildingprojects/"
  weight = 70
```

**Comment by hacdias** [comment]
Hello @AstonDavies,

This seems to be a problem with the TOML Marshaller/Parser. The same content can be Marshalled using the JSON and YAML Marshallers flawlessly. I'll try some more things.

**Comment by hacdias** [comment]
Done @AstonDavies 😄
