### ISSUE TITLE
no action found for directive 'filemanager' with server type 'http' (missing a plugin?)

### ISSUE THREAD

**Issue by iscraft** [hacdias/caddy-filemanager#71]
use caddy 0.9.5 FreeBSD ARMv7
select filemanager in download page(https://caddyserver.com/download)
but error is : no action found for directive 'filemanager' with server type 'http' (missing a plugin?)
Cddyfile:
https://example.com {
tls example@gmail.com
startup /usr/local/sbin/php-fpm -c /usr/local/etc/php.ini -y /usr/local/etc/php-fpm.conf &
root /usr/local/www
gzip
fastcgi / 127.0.0.1:9000 php {
ext .php
}
filemanager /share {
show           /usr/local/www/share
allow_new      true
allow_edit     true
allow_commands true
}
}
https://www.example.com {
redir https://example.com
}
this file is working for 0.9.4

**Comment by hacdias** [comment]
This issue is not related with this repository but with the build server. Anyway, I also downloaded it from that website and it works. I would suggest you to talk with @mholt, who is maintaining the website, if the error persists.
