### ISSUE TITLE
Display PDF inline

### ISSUE THREAD

**Issue by sinni800** [hacdias/caddy-filemanager#72]
Currently PDFs would only show a "download" link, but wouldn't it possible to show them inline like an image?

You would have to use an iframe (ew, I know), but that's the way to let the browser take care of rendering it. All browsers have PDF renderers built in now so it wouldn't be much trouble. They also have save buttons in the PDF viewers usually.

It would just need to be served with raw=true in that case.

Looks like the following image if I just replace the download link with the iframe: https://i.imgur.com/XQr9Ice.png though maybe not limit it to 960px.

EDIT: I've seen that alternatively, `<object data="url">` should work just fine, but I haven't tested extensively yet.

**Comment by hacdias** [comment]
Hello @sinni800,

It is, indeed, something interesting to add but I've to check the best styles to do it first. I'll add it ASAP 😄
