### ISSUE TITLE
Can't upload larger files

### ISSUE THREAD

**Issue by sinni800** [hacdias/caddy-filemanager#73]
I am unsure if this is a caddy or filemanager thing, I hope I got this right though.

So when I try to upload larger files, it will just stop at a random place (the uplaod button turns into an X) and put this error in the console (on Chrome): 

    PUT https://bla/fs/file.pdf net::ERR_CONNECTION_CLOSED. 

This error appears with any browser but only Chrome actually spat out the error message.

I am trying with a 12 megabyte file, it randomly breaks at any progress. The request time is also random, ranging from 5 seconds to (longest I've seen) 12.65s. 

This leads me to believe it's not a timeout in Caddy or anything. 

Currently on revision a9aaba5

**Comment by hacdias** [comment]
Hello @sinni800! 

That's a really nice question and I really don't know what I should answer you. I'm not the one who's doing the upload. It's a golang native package called `webdav`. I'll take a look at it. But it seems it must be a limit somewhere on the server side. IDK.

**Comment by sinni800** [comment]
Yeah I tried looking if it was anywhere else in the pipeline... I wish someone else could reproduce it first

**Comment by hacdias** [comment]
Hello @sinni800! I tried running FM on my pc and uploading a 135 MB file. It worked. I know it is on my PC so the speed is really fast but now I wonder if it can be a timeout or something on server side.

**Comment by sinni800** [comment]
Do you think it would help if I gave you a file manager running on my server for testings?

**Comment by hacdias** [comment]
I'm not really sure whether or not it would help. I can deploy it on a server myself to test and check if I get any error. I'll ping you later with my results.

**Comment by sinni800** [comment]
I've been testing some and now I almost think something different is up entirely, but I don't even remotely know what. I've seen downloads do the same thing now.

**Comment by hacdias** [comment]
No problem. I'll leave this issue open if you get more details. If you think it can be related to Caddy, I think we could ping Matt.

**Comment by sinni800** [comment]
Alright, after testing with Nginx, with and without SSL and Caddy, with and without SSL (I had a hunch about SSL there), I can conclude it happens only on Caddy and it doesn't matter if I use Filemanager or not. 

All my transfers, up or down, break after a few seconds... I never had any big files so this is a new one to me.

**Comment by hacdias** [comment]
@sinni800 right now they only go into the Caddy builder when @mholt updates the repository on the server. But sooner it will be the plugin developers who control when they're updated on the server. 😄 It'll be great!

**Comment by mholt** [comment]
Did you disable timeouts and try anyway? `timeouts none`

**Comment by sinni800** [comment]
Hi, @mholt 

From my first test, that seems to actually solve it, but why is a timeout causing a problem with a *down*load anyway? For uploads I can see request timeouts causing a problem.

**Comment by mholt** [comment]
There are different timeouts because there are different ways to attack a server. There are read, read header, write, and idle timeouts. (Idle doesn't take effect until Go 1.8.) A write timeout mitigates attacks from clients who download files intentionally very slowly.

**Comment by sinni800** [comment]
Hm, I see. But that helped. I will set the timeouts more precisely between the four timeouts... I didn't know I have to set it up for large downloads, too

**Comment by mholt** [comment]
It needs better highlighting in the Caddy documentation, too. It's a new thing. We'll flush that out.

**Comment by sinni800** [comment]
Alright, good to hear. Would be a shame if more people run into this in the future.

**Comment by hacdias** [comment]
Thanks @mholt 😄 
I'll close this now @sinni800!
