### ISSUE TITLE
When going backwards in directories, a trailing slash will not be attached

### ISSUE THREAD

**Issue by sinni800** [hacdias/caddy-filemanager#74]
So when browsing directories, a trailing slash will always be there. As soon as you go back in directories though, the trailing slash will not be added to the path. 

So you are in `/path/`, when you enter the folder `dir`, you will have `/path/dir/` in the path. When you use the "go back" feature to go back to `/path/`, you will end up with `/path`

A tiny bug that is just inconsequent behaviour and does't break anything, but would be nice to have fixed for consistency.

**Comment by hacdias** [comment]
Hey @sinni800! Thanks for reporting this. I'll fix it as soon as I can 😄

**Comment by hacdias** [comment]
Done 😃
