### ISSUE TITLE
Names containing a backslash don't work

### ISSUE THREAD

**Issue by pepa65** [hacdias/caddy-filemanager#75]
File Manager. Revision a9aaba5.

I'm trying out to what extent names are working correctly in caddy-filemanager. When I click (double-click??) on a file or directory name with a backslash `\` character in it, it will result in a 404.

Caddyfile:
```text
localhost:8008 {
        filemanager / {
                show /home/pp/.Atst/
                allow_new true
                allow_edit true
                allow_commands false
        }
}
```

I had hoped it would work, ie. show the content of the file or directory.

I got the 404 page instead.

Reproduce by `mkdir -p /home/pp/.Atst/pp\\qq`, putting the above listed Caddyfile in `/home/pp/.Atst/Caddyfile` and then `(cd /home/pp/.Atst; caddy)`

**Comment by hacdias** [comment]
This is going to be hard to test since I'm using Windows and it doesn't even allow me to create a file with a backslash on its name!

**Comment by pepa65** [comment]
I'm happy to help test. But a virtual machine is super easy to set up. Install any quick Linux (I use Ubuntu) and use `wget -qO- getcaddy.com |bash -s filemanager` and you're good to go.

**Comment by hacdias** [comment]
Yes, I'm downloading mint atm. Thanks ;)

**Comment by pepa65** [comment]
Thanks for working on this. I have reviewed all web-interfaced filemanagers I could lay my hands on, and they all did worse than caddy-filemanager. It can deal with almost anything -- except backslashes..! (I used ` !"#$%&'()*+,:;<=>?@\|[]` as one of my test filenames, and if I removed the backslash, caddy-filemanager worked!)

**Comment by hacdias** [comment]
Thanks too 😄 I think the problem is that I'm not enconding the URL but I'm not sure. I'll check it.

**Comment by pepa65** [comment]
I think you're encoding what you need to, except for the backslash.

**Comment by hacdias** [comment]
The thing is, the URL is correctly encoded. The error is: ```stat pp/dd: no such file or directory```. Can it be a problem in Go? 😕 I'm going to check.

**Comment by hacdias** [comment]
Oh, I was the one who caused this problem :|

```
i.Path = u.Scope + i.VirtualPath
i.Path = strings.Replace(i.Path, "\\", "/", -1)
i.Path = filepath.Clean(i.Path)
```

**Comment by hacdias** [comment]
The question is: why have I done that?

**Comment by hacdias** [comment]
I think it might have been to let the users put the URL with backslashes but it doesn't make any sense :| I'll remove that second line though.

**Comment by hacdias** [comment]
Yup, it works now. I'll push this fix.

**Comment by pepa65** [comment]
Awesome, thanks a lot for all your trouble.

**Comment by hacdias** [comment]
No problem!
