### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by pztrn** [hacdias/caddy-filemanager#76]
Hello.

I'm trying to install filemanager plugin in Caddy by hand, as I need custom Caddy build. According to [this page](https://github.com/mholt/caddy/wiki/Extending-Caddy) this can be done by adding import statement to run.go. But if I try to do that (as well as install any plugin that requires filemanager, like hugo) - I got following error:

```
# github.com/hacdias/caddy-filemanager/assets
/tmp/caddybuilder-gopath/src/github.com/hacdias/caddy-filemanager/assets/assets.go:19: undefined: Asset
```

How to install this plugin properly and why there is no instructions about that in README.md?

**Comment by hacdias** [comment]
There is a specific section on the wiki about that: https://github.com/hacdias/caddy-filemanager/wiki#developers .
