### ISSUE TITLE
User specific allow/disallow not granted.

### ISSUE THREAD

**Issue by sugacube** [hacdias/caddy-filemanager#81]
### 1. Which revision of File Manager are you running (check the footer on any page)?
Served with Caddy and File Manager. Revision 02e2bec.

### 2. What are you trying to do?
user authentication, disallow a user to upload a file

### 3. What is your entire Caddyfile?
```:8080 {
	basicauth /files user pass
	basicauth /files user2 pass
	filemanager /files {
		show files/
		user2:
		allow_new false
		allow_edit false
	}
}
```

### 4. What did you expect to see?
open browser, go to page localhost:8080/files, login with user=user2, password=pass
Expect that
1) upload of a file is not possible,
2) edit of a file is not possible
for example , when removing line "user2" in the caddyfile, the upload and edit icons will not be shown.

### 5. What did you see instead (give full error messages and/or log)?
user2 can upload and edit a file.

### 6. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
1) create a folder with
- caddy.exe
- Caddyfile (see above)
- empty folder /files
2) launch caddy.exe
3) browse to localhost:8080

**Comment by hacdias** [comment]
I'm just going to merge this with #81 because they are probably are the same bug.
