### ISSUE TITLE
It would be useful to mention the importance of the caddyserver general timeout setting

### ISSUE THREAD

**Issue by sugacube** [hacdias/caddy-filemanager#82]
This may be a minor issue but it would be useful to mention the importance of the general timout setting in caddyserver when using file manager. Maybe in the file manager documentation section.

Default timeouts of caddyserver are quite low when performing file upload/download of large files.

When an upload fails in file manager, it is not immediately obvious this may be caused by the caddyserver time out value.

Another remark, i'm not sure this should be considered a bug or a feature:
When an upload fails, this is not made very clear (quick flash of an X), and the partially uploaded file is left uploaded.

**Comment by hacdias** [comment]
Hello @sugacube! Thanks for the suggestion. I've added a note to this repository's README which is going to be the main documentation soon (after 20th April I guess).
