### ISSUE TITLE
filemanager: can't disallow new file upload with basicauth

### ISSUE THREAD

**Issue by windymindy** [hacdias/caddy-filemanager#83]
1. What version of Caddy are you running (caddy -version)?

CADDY 0.9.5 32-bit for windows

2. What are you trying to do?

I was checking https://caddyserver.com/docs/filemanager example with bassicauth right at the bottom of the doc.

3. What is your entire Caddyfile?

filemanager /admin {
show ./
allow_commands false
admin:
allow_commands true
allow_command rm
allow_command mv
allow dotfiles
manager:
block /admin/financial
editor:
allow_new false
block /admin/financial
}

basicauth /admin admin pass
basicauth /admin manager pass
basicauth /admin editor pass

4. How did you run Caddy (give the full command and describe the execution environment)?

5. Please paste any relevant HTTP request(s) here.

6. What did you expect to see?

I expected user editor not to be able to upload new files through filemanager.

7. What did you see instead (give full error messages and/or log)?

Despite what is said in the doc, editor can successfuly upload new files.

8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Just run Caddy with sample Caddyfile. Navigate to /admin, enter editor/pass credentials and drag any file into browser window or press Upload button.

**Comment by hacdias** [comment]
Hey @windymindy! Sorry for the delay. I'll be some days away from home and hopefully Saturday I'll be able to try this. 😄

**Comment by hacdias** [comment]
Hello @windymindy! Here, when I open it with editor's account, I don't even see an upload button :/

**Comment by hacdias** [comment]
What's the information you have in the bottom of the page (sth like `Served with Caddy and File Manager. Revision xxxxxx.`)? What's the revision?

**Comment by windymindy** [comment]
Hello there!
I have made up a quick video that reproduces the problem, where Caddy with Filemanager plugin is installed and run from scratch.
I pass basic auth with editor's credentials and successfuly upload a file.
Served with Caddy and File Manager. Revision 02e2bec.
Hope this helps.

https://youtu.be/VjGGPWMVE9M

**Comment by hacdias** [comment]
Hello @windymindy! I just run it with the version from caddyserver.com and the latest one. You're right. The one we download from the website has that bug, but in the newest revision that bug doesn't happen anymore. 😄 After 20th April, when the new Caddy website is released, you'll be able to download the newest version, right @mholt? 

Hope it doesn't cause you any troubles. You can also build it from source.

**Comment by hacdias** [comment]
This is getting a lot stranger than I would have thought. The same version, from caddyserver.com doesn't work, and if built from source, works. This is really strange but I think I figured out a way for it to work: I saw the code of basicauth and they use a context variable to pass the username.

**Comment by hacdias** [comment]
So, I just took my conclusions and figured everything out 😄 

It doesn't work on Caddy 0.9.5 because the `basicauth` directive removes the authentication header to prevent the upstream middleware to get the passwords and eventually leak them [(ref)](https://github.com/mholt/caddy/blob/v0.9.5/caddyhttp/basicauth/basicauth.go#L62).

Right now, it sends the username in the request as a context variable [(ref)](https://github.com/mholt/caddy/blob/master/caddyhttp/basicauth/basicauth.go#L66) and that is what I'm going to use to fix this issue. I believe it will be usable after 20th April. I'll just wait for @mholt to tell me if I'm right about this. After that, I'll close this issue 😄

**Comment by mholt** [comment]
@hacdias Correct, on master Caddy no longer removes the Authorization header and sets the username on the request context. And the new version will be available on April 20.

**Comment by hacdias** [comment]
Thanks @mholt! So, I'll close this issue because it is already fixed. We just have to wait for the new version 😄
