### ISSUE TITLE
Feature request: Option to make search case-insensitive

### ISSUE THREAD

**Issue by tkfu** [hacdias/caddy-filemanager#88]
Case-sensitive search is good for some use cases, bad for others. It would be nice to at least have the option of doing case-insensitive searches, either through a check box next to the search bar, or by setting a config option.

**Comment by hacdias** [comment]
I'll leave this opened and it is, indeed, a good feature to have 😄 I'll dig on this as soon as I can!

**Comment by hacdias** [comment]
Hello @tkfu!

Would you like to make a case insensitive search like this:

```search terms... case:insensitive```

It would be like an option, just like we do on Google search to create some filters.

**Comment by hacdias** [comment]
Already available on `caddyserver.com`!
