### ISSUE TITLE
What is the show path relative to?

### ISSUE THREAD

**Issue by mqus** [hacdias/caddy-filemanager#89]
I really think that setting the default baseurl to `/` is misleading and outright dangerous... It would be much better to first consider the root Directory set by the Caddyfile(or the Caddyfile location).
There are 3 main benefits which would come with this change:
1. No security implications by default (to have read access to the `/` directory of any server/home pc is not a good idea, as you can read most of the config files(on Unix) and much more)
2. Less confusion caused by the differences between the root directive, the baseurl, the show-location and the on-location (well, mainly the first two)
3. Having to maintain only one path in the Caddyfile (less error-prone and easier)

Are there reasons for setting the default to `/` ?

(This change was also considered in #10 but then closed)

**Comment by mqus** [comment]
Whoops, I didn't understand the documentation correctly, sorry for that, my question should have to be changed. in the documentation is mentioned that the path in show can be relative, relative to what? 

currently my caddyfile looks like that:
`https://x.x.x:1320, :1319 {

	root /srv2/http-browse
	filemanager {
		webdav /webdav
	}
	browse
	timeouts 0 

	basicauth / xxx xxx
	log /var/log/caddy.log
}`

and when opening, the filemanager shows me my server root directory (`/`) and webdav doesn't work.
(Output: `<?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:"><D:response><D:href>/webdav</D:href><D:propstat><D:prop><D:getlastmodified>Sun, 02 Apr 2017 15:56:14 GMT</D:getlastmodified><D:supportedlock><D:lockentry xmlns:D="DAV:"><D:lockscope><D:exclusive/></D:lockscope><D:locktype><D:write/></D:locktype></D:lockentry></D:supportedlock><D:resourcetype><D:collection xmlns:D="DAV:"/></D:resourcetype><D:displayname></D:displayname></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>Internal Server Error`)
What did I miss? I will try to use the show option now(that will propably work) but should that really be necessary?

My original goal was to add an webdav interface to my simple fileserver (previously only with the browse directive) and i would really like to continue using the browse directive if possible as I don't need the features of the filemanager itself.

**Comment by hacdias** [comment]
The `show` option can be either an absolute path or a relative path to the location where Caddy is being executed.

In your Caddyfile, you can replace what you have:

```
filemanager {
	webdav /webdav
}
```

for 

```
filemanager 
```

This is because the option `webdav` has `/webdav` by default and you don't need to specify if you want to maintain that path.

Hope it helped 😄 
Feel free to ask more questions
