### ISSUE TITLE
Dead link.

### ISSUE THREAD

**Issue by k0nsl** [hacdias/caddy-filemanager#9]
The link in the project description returns a 404.

**Comment by hacdias** [comment]
I know. It's "dead" because the new version of Caddy wasn't released yet. It should be released in a few weeks/days and then the link will be available. Thanks anyway :)

**Comment by MSF-Jarvis** [comment]
It's up, might wanna change it now

**Comment by k0nsl** [comment]
That's great news. I am really excited to test it out :)

**Comment by MSF-Jarvis** [comment]
Don't, it's addictive.

**Comment by hacdias** [comment]
This issue was moved to hacdias/filemanager#120
