### ISSUE TITLE
File information dialog is broken on Firefox

### ISSUE THREAD

**Issue by PaulsBarkans** [hacdias/caddy-filemanager#92]
![screenshot from 2017-05-28 14-25-46](https://cloud.githubusercontent.com/assets/1485739/26528343/75e8c6d8-43b2-11e7-8664-49d85d90d499.png)

Caddy server (version 0.10.3) bundled with File Manager from caddyserver.com (downloaded today).
Firefox 53.0.2 (64-bit)
OS: Linux Mint 18.1 (based on Ubuntu 16.04)

P.S. It's ok on Chrome.

**Comment by hacdias** [comment]
Can you please tell me if there is any error on the developer tools? 

Oh, and one more question: does the bar shows up like that on Chrome too? (with two lines of icons)

**Comment by PaulsBarkans** [comment]
Error in FF console:
```
TypeError:` xml.getElementsByTagName(...)[0] is undefined
Stack trace:
infoEvent/<@http://localhost:2015/_filemanagerinternal/js/common.js:348:56
promise callback*infoEvent@http://localhost:2015/_filemanagerinternal/js/common.js:342:3
EventListener.handleEvent*@http://localhost:2015/_filemanagerinternal/js/common.js:607:3
EventListener.handleEvent*@http://localhost:2015/_filemanagerinternal/js/common.js:594:1
```

No error on Chrome and dialog also shows ok on Chrome.

**Comment by hacdias** [comment]
I'll fix this as soon as I can 😄

**Comment by hacdias** [comment]
Fixed and deployed 😄
