### ISSUE TITLE
Alternative CSS ? 

### ISSUE THREAD

**Issue by rgarrigue** [hacdias/caddy-filemanager#93]
Hello

Thanks for the plugin, very nice job. I saw in the README.md plan for a doc to explain how to edit CSS. Is there already some alternative css I could try ? 

Best regards,

**Comment by hacdias** [comment]
Hello @rgarrigue! Do you want to add your own stylesheet or make a custom Caddy build with FileManager? Probably the first would be the easier and it can be done with the `styles` option.

**Comment by rgarrigue** [comment]
Hi @hacdias 

The `styles` is exactly what I had in mind. So it's all about c/c https://raw.githubusercontent.com/hacdias/caddy-filemanager/master/_embed/public/css/styles.css and customize it, am I right ? 

Is there already by any chance some alternative ? I'm very far from being a CSS pro, I'ld find it easier to make a diff between two 'valid' css to see the relevant stuff right away :-)

Thanks,

**Comment by hacdias** [comment]
Hello!

The file you mentioned is _always_ present. The `styles` option lets you add your own stylesheet so you can override the defaults. Your stylesheet will be prioritized over the default's.

So, if your own stylesheet is empty, File Manager will be shown as usual. But if you add some rule that overrides another, you'll see the overriding live too.

I don't if I explained well, but let me know!

**Comment by rgarrigue** [comment]
Ok, gonna try fiddling with that whenever I got some free time. Thanks !

**Comment by hacdias** [comment]
You're welcome. If you need something else, just tell me.
